from __future__ import annotations

MATCH_RATE_WARNING = 0.95
MATCH_RATE_FAIL = 0.80

DUPLICATE_RATIO_WARNING = 0.01
DUPLICATE_RATIO_FAIL = 0.05

ROW_INFLATION_RATIO_WARNING = 0.01
ROW_INFLATION_RATIO_FAIL = 0.05

VALIDATION_ERROR_WEIGHT = 30
VALIDATION_WARNING_WEIGHT = 8
LOW_MATCH_WARNING_WEIGHT = 15
LOW_MATCH_FAIL_WEIGHT = 40
DUPLICATE_WARNING_WEIGHT = 10
DUPLICATE_FAIL_WEIGHT = 35
ROW_INFLATION_WARNING_WEIGHT = 15
ROW_INFLATION_FAIL_WEIGHT = 40

RISK_STATUS_AMBER_MIN = 20
RISK_STATUS_RED_MIN = 60

DEFAULT_PREFLIGHT_MODE = "strict"  # "strict" or "review"

